// students

export const GET_STUDENT = "get/GET_STUDENT";
export const GET_STUDENT_BY_ID = "get/GET_STUDENT_BY_ID";
export const GET_DISABLE_STUDENT = "get/GET_DISABLE_STUDENT";
export const POST_STUDENT = "post/POST_STUDENT";
export const PATCH_STUDENT = "patch/PATCH_STUDENT";
export const DELETE_STUDENT = "delete/DELETE_STUDENT";
export const PATCH_ENABLE_DISABLE_STUDENT = "patch/PATCH_ENABLE_DISABLE_MIDDLEWARE";

// staffs

export const GET_DEPARTMENT_DROPDOWN = "get/GET_DEPARTMENT_DROPDOWN"
export const GET_DESIGNATION_DROPDOWN = "get/GET_DESIGNATION_DROPDOWN"
export const GET_STAFF_TYPE_DROPDOWN = "get/GET_STAFF_TYPE_DROPDOWN"
export const GET_STAFFS = "get/GET_STAFFS"
export const GET_DISABLED_STAFFS = "get/GET_DISABLED_STAFFS"

// staff directory

export const GET_ALL_CONTRACT = "get/GET_ALL_CONTRACT";
export const GET_ALL_MARITIAL_STATUS = "get/GET_ALL_MARITIAL_STATUS";
export const GET_ALL_ROLES = "get/GET_ALL_ROLES";
export const GET_TEACHER_BY_ID = "get/GET_TEACHER_BY_ID";
export const PATCH_UPDATE_STAFF_BY_ID = "patch/PATCH_UPDATE_STAFF_BY_ID";
export const POST_TEACHER = "post/POST_TEACHER";
export const GET_EDIT_STAFF_DIRECTORY = "get/GET_EDIT_STAFF_DIRECTORY";
export const PATCH_ENABLE_DISABLE_TEACHER =
  "patch/PATCH_ENABLE_DISABLE_TEACHER";
export const GET_ALL_TEACHER_DISABLE_STAFF =
  "get/GET_ALL_TEACHER_DISABLE_STAFF";

//STAFF CENTRALIZED
// export const GET_DEPARTMENT_DROPDOWN = "get/GET_DEPARTMENT_DROPDOWN"
export const GET_STAFF_DROPDOWN = "get/GET_STAFF_DROPDOWN"
// export const GET_DESIGNATION_DROPDOWN = "get/GET_DESIGNATION_DROPDOWN"
export const GET_STAFF_LIST="get/GET_STAFF_LIST"
// staff master

// export const GET_STAFF_DESIGNATION_DROPDOWN =
//   "get/GET_STAFF_DESIGNATION_DROPDOWN";
// export const GET_STAFF_DEPARTMENT_DROPDOWN =
//   "get/GET_STAFF_DEPARTMENT_DROPDOWN";
// export const GET_STAFF_TYPE_DROPDOWN = "get/GET_STAFF_TYPE_DROPDOWN";

//staff disable
export const GET_ALL_TEACHER_DISABLESTAFF = "get/GET_ALL_TEACHER_DISABLESTAFF";
export const GETSEARCHSTAFF = "getsearchstaff/GETSEARCHSTAFF";
export const PATCH_ENABLEDISABLE_TEACHER = "patch/PATCH_ENABLEDISABLE_TEACHER";

//applyleave
export const GET_APPLYLEAVE_DATA = "get/GET_APPLYLEAVE_DATA";
export const GETSEARCHLEAVEAPPLY = "get/GETSEARCHLEAVEAPPLY";
export const GET_ONELEAVE_DATA = "get/GET_ONELEAVE_DATA";
export const GET_LEAVE_TYPE = "get/GET_LEAVE_TYPE";
export const POST_APPLY_LEAVE = "post/POST_APPLY_LEAVE"
export const PATCH_ONELEAVE_DATA = "patch/PATCH_ONELEAVE_DATA"

//academics

export const GET_STUDENTLIST ="get/GET_STUDENTLIST"
export const POST_STUDENTLIST = "post/POST_STUDENTLIST"
export const GET_CLASS = "get/GET_CLASS"
export const GET_SECTION ="get/GET_SECTION"
export const GET_TEACHER ="get/GET_TEACHER"
export const GET_SUBJECT ="get/GET_SUBJECT"
export const PATCH_STUDENTLIST = "patch/PATCH_STUDENTLIST"
export const GET_CLASS_TIMETABLE = "get/GET_CLASS_TIMETABLE"
export const GET_TEACHER_TIMETABLE ="get/GET_TEACHER_TIMETABLE"
export const GET_ALL_TABLEDATA = "get/GET_ALL_TABLEDATA"
export const POST_ASSING_TEACHER = "post/POST_ASSING_TEACHER"
export const PATCH_ASSING_TEACHER ="patch/PATCH_ASSING_TEACHER"
export const DELETE_ASSING_TEACHER = "delete/DELETE_ASSING_TEACHER"
export const GET_ALLATTENDANCE_TABLE ="get/GET_ALLATTENDANCE_TABLE"
export const GET_ATTENDANCE = "get/GET_ATTENDANCE"
export const POST_ASSING_STUDENTS = "post/POST_ASSING_TEACHER"
export const PATCH_ASSING_STUDENTS ="patch/PATCH_ASSING_TEACHER"
export const DELETE_ASSING_STUDENTS = "delete/DELETE_ASSING_TEACHER"
export const GET_PROMOTESTUDENT_TABLE = "get/GET_PROMOTESTUDENT_TABLE"
export const GET_ALLHOMEWORK_TABLE = "get/GET_ALLHOMEWORK_TABLE"
export const GET_HOMEWORK = "get/GET_HOMEWORK"
//announcement communication
export const GET_ALL_ANNOUNCEMENT_DATA="get/GET_ALL_ANNOUNCEMENT_DATA"
export const POST_ANNOUNCEMENT_DATA="post/POST_ANNOUNCEMENT_DATA"
export const EDIT_ANNOUNCEMENT_DATA="edit/EDIT_ANNOUNCEMENT_DATA"
export const VIEW_ANNOUNCEMENT_DATA="view/VIEW_ANNOUNCEMENT_DATA"
export const DELETE_ANNOUNCEMENT_DATA="delete/DELETE_ANNOUNCEMENT_DATA"

//EMAIL
export const GET_ALL_EMAIL_DATA="get/GET_ALL_EMAIL_DATA"
export const POST_EMAIL_DATA="post/POST_EMAIL_DATA"
export const EDIT_EMAIL_DATA="edit/EDIT_EMAIL_DATA"
export const VIEW_EMAIL_DATA="view/VIEW_EMAIL_DATA"
export const DELETE_EMAIL_DATA="delete/DELETE_EMAIL_DATA"

//SMS
export const GET_ALL_SMS_DATA="get/GET_ALL_SMS_DATA"
export const POST_SMS_DATA="post/POST_SMS_DATA"
export const EDIT_SMS_DATA="edit/EDIT_SMS_DATA"
export const VIEW_SMS_DATA="view/VIEW_SMS_DATA"
export const DELETE_SMS_DATA="delete/DELETE_SMS_DATA"

//LOGINCREDENTIALS
export const GET_ALL_LOGINCREDENTIALS_DATA="get/GET_ALL_LOGINCREDENTIALS_DATA"
export const POST_LOGINCREDENTIALS_DATA="post/POST_LOGINCREDENTIALS_DATA"
export const EDIT_LOGINCREDENTIALS_DATA="edit/EDIT_LOGINCREDENTIALS_DATA"
export const VIEW_LOGINCREDENTIALS_DATA="view/VIEW_LOGINCREDENTIALS_DATA"
export const DELETE_LOGINCREDENTIALS_DATA="delete/DELETE_LOGINCREDENTIALS_DATA"
//GET_ALL_LESSONPLAN_DATA
export const GET_ALL_LESSONPLAN_DATA="get/GET_ALL_LESSONPLAN_DATA"
//GET_ALL_SYLLABUSMASTER_DATA

export const GET_ALL_SYLLABUSMASTER_DATA="get/GET_ALL_SYLLABUSMASTER_DATA"
export const GET_ALL_SYLLABUSSTATUS_DATA="get/GET_ALL_SYLLABUSSTATUS_DATA"


