import {
  BLOOD_GROUP_API_ID,
  CATEGORY_API_ID,
  CLASS_API_ID,
  DISABLE_REASON_API_ID,
  HOUSE_API_ID,
  RELIGION_API_ID,
  SCHOOL_DIVISION_API_ID,
  SECTION_API_ID,
  DEPARTMENT_API_ID,
  DESIGNATION_API_ID,
  GENDER_API_ID,
  BRANCH_API_ID,
} from "../utility/constant";

export const APIROUTES = {
  SIDEBAR: {
    GET_SIDEBAR: "getData",
    GET_SIDEBAR_LIST: "common/modules/tree",
    GET_SIDEBAR_LIST_USER: "common/modules/my-modules",
    GET_MODULE_ACCESS: "common/modules/access-list",
  },
  AUTH: {
    POST_SIGNUP_API: "users/register",
    POST_LOGIN_API: "common/users/login",
  },
  COMMON: {
    GET_COUNTRY: "common/countries/",
    GET_STATES: "common/states?countryId=",
    GET_CITY: "common/cities?stateId=",
    GET_YEAR_TYPE: `common/dynamic-masters/data/${BRANCH_API_ID}`,
  },
  USER: {
    GET_USER_LIST_API: "users/all-users?",
  },
  COMPANY: {
    GET_ALL_COMPANY: "common/companies/",
    GET_ALL_LEGAL_ENTITY: "common/legalEntity-type/",
    GET_ALL_INDUSTRY: "common/industry-type/",
    POST_COMPANY: "common/companies/",
    GET_COMPANY_BY_ID: "common/companies/",
    PATCH_COMPANY_MIDDLEWARE: "common/companies/",
    DELETE_COMPANY_BY_ID: "common/companies/",
  },
  BRANCH: {
    GET_ALL_BRANCH_TYPE: "common/branch-type/",
    POST_BRANCH: "common/branches/",
    GET_ALL_BRANCH: "common/branches/",
    GET_COMPANYID_BRANCH: "common/branches/by-companyId",
    GET_BRANCH_BY_COMPANY_ID: "common/branches/by-companyId",
    GET_BRANCHBY_ID: "common/branches/",
    PATCH_BRANCH: "common/branches/",
    DELETE_BRANCH_BY_ID: "common/branches/",
    GET_CURRENCY: "common/currencies",
    GET_TIMEZONE: "common/timezones",
  },
  TEMPLATES: {
    GET_LIST_ACCESS_TEMPLATES: "common/access-template/",
    GET_LIST_OF_USERS_ACCESS_TEMPLATES: "common/users/users-of-template/",
    POST_TEMPLATE_CARD: "common/access-template/",
    PATCH_TEMPLATE_CARD: "common/access-template/",
    DELETE_TEMPLATE_CARD: "common/access-template/",
    DETAIL_TEMPLATE_CARD: "common/access-template/",
    ADD_DETAIL_TEMPLATE_CARD: "common/access-template/base-template",
    ASSIGN_TEMPLATE_USERS: "common/users/assign-access-template",
  },
  USER_ACCESS: {
    GET_ALL_TEMPLATE_API: "common/access-template/",
    GET_ALL_USERS_BY_COMPANY_API: "common/users/all-users-company/",
    POST_USER_ACCESS_API: "common/users/create",
    GET_USER_ACCESS_BY_ID_API: "common/users/",
    // GET_DEPARTMENT_API: "common/department",
    GET_BLOOD_GROUPS_API: `common/dynamic-masters/data/${BLOOD_GROUP_API_ID}`,
    // GET_DESIGNATION_API: "common/designation/designations-of-department/",
    GET_REPORTING_API: "common/users/all-users-company/",
    EDIT_USER_ACCESS_API: "common/users/",
    DELETE_USER_ACCESS_API: "common/users/",
    GET_GENDER_OPTIONS_API: `common/dynamic-masters/data/${GENDER_API_ID}`,
    GET_DEPARTMENT_API: `common/dynamic-masters/data/${DEPARTMENT_API_ID}`,
    GET_DESIGNATION_API: `common/dynamic-masters/data/${DESIGNATION_API_ID}`,

    // POST_USER_ACCESS_API:"common/users/create"
  },
  DYNAMICMASTER: {
    GET_MASTER_DROPDOWN: "common/dynamic-masters/",
    GET_DYNAMIC_MASTER_DATA_API: "common/dynamic-masters/data/",
    POST_MASTER_VALUES: "common/dynamic-masters/data",
    PATCH_MASTER_VALUES_API: "common/dynamic-masters/data/",
    DELETE_MASTER_VALUES_API: "common/dynamic-masters/data/",
    GET_BLOOD_GROUP_DROPDOWN: `common/dynamic-masters/data/${BLOOD_GROUP_API_ID}`,
    GET_CLASS_DROPDOWN: `common/dynamic-masters/data/${CLASS_API_ID}`,
    GET_SECTION_DROPDOWN: `common/dynamic-masters/data/${SECTION_API_ID}`,
    GET_GENDER_DROPDOWN: `common/dynamic-masters/data/${GENDER_API_ID}`,
    GET_SCHOOL_DIVISION_DROPDOWN: `common/dynamic-masters/data/${SCHOOL_DIVISION_API_ID}`,
    GET_RELIGION_DROPDOWN: `common/dynamic-masters/data/${RELIGION_API_ID}`,
    GET_CATEGORY_DROPDOWN: `common/dynamic-masters/data/${CATEGORY_API_ID}`,
    GET_HOUSE_DROPDOWN: `common/dynamic-masters/data/${HOUSE_API_ID}`,
    GET_DISABLE_REASONS_DROPDOWN: `common/dynamic-masters/data/${DISABLE_REASON_API_ID}`,
  },
  YEAR_MASTER: {
    GET_YAER_MASTER_DATA_API: "common/years/",
    POST_YAER_MASTER_FORM_API: "common/years/",
    GET_YEAR_TYPE_API: "common/dynamic-masters/data/MS0019",
  },
};
