export const mockAttendanceSelectData = {
  January: [
    { day: 1, value: 8, goal: 8, status: "Present" },
    // { day: 2, value: 3, goal: 8, status: "Late" },
    { day: 3, value: 8, goal: 8, status: "Absent" },
    // { day: 4, value: 5, goal: 8, status: "Half Day" },
    { day: 5, value: 8, goal: 8, status: "Holiday" },
    // Continue for all days...
  ],
  February: [
    { day: 1, value: 7, goal: 8, status: "Present" },
    // { day: 2, value: 6, goal: 8, status: "Late" },
    { day: 3, value: 8, goal: 8, status: "Absent" },
    // { day: 4, value: 4, goal: 8, status: "Half Day" },
    { day: 5, value: 8, goal: 8, status: "Holiday" },
    // Continue for all days...
  ],
  March: [
    { day: 1, value: 8, goal: 8, status: "Present" },
    { day: 2, value: 8, goal: 8, status: "Absent" },
    // { day: 3, value: 6, goal: 8, status: "Late" },
    { day: 4, value: 8, goal: 8, status: "Holiday" },
    { day: 5, value: 4, goal: 8, status: "Half Day" },
    // Continue for all days...
  ],
  September: [
    { day: 1, value: 8, goal: 8, status: "Present" },
    // { day: 2, value: 4, goal: 8, status: "Half Day" },
    { day: 3, value: 8, goal: 8, status: "Absent" },
    { day: 4, value: 8, goal: 8, status: "Holiday" },
    { day: 5, value: 8, goal: 8, status: "Present" },
    // { day: 6, value: 6, goal: 8, status: "Late" },
    { day: 7, value: 8, goal: 8, status: "Present" },
    { day: 8, value: 8, goal: 8, status: "Absent" },
    // Continue for all days...
  ],
  // Add more months as necessary...
};
export const mockstudentlistData = [
  { id: 1, rollNumber: '101', studentName: 'Alice Johnson', admissionNumber: 'A123' },
  { id: 2, rollNumber: '102', studentName: 'Bob Smith', admissionNumber: 'B456' },
  { id: 3, rollNumber: '103', studentName: 'Charlie Brown', admissionNumber: 'C789' },
  { id: 4, rollNumber: '104', studentName: 'David Wilson', admissionNumber: 'D101' },
  { id: 5, rollNumber: '105', studentName: 'Emma Davis', admissionNumber: 'E202' },
  { id: 6, rollNumber: '106', studentName: 'Fiona Garcia', admissionNumber: 'F303' },
  { id: 7, rollNumber: '107', studentName: 'George Martinez', admissionNumber: 'G404' },
  { id: 8, rollNumber: '108', studentName: 'Hannah Thompson', admissionNumber: 'H505' },
  { id: 9, rollNumber: '109', studentName: 'Isaac Anderson', admissionNumber: 'I606' },
  { id: 10, rollNumber: '110', studentName: 'Julia White', admissionNumber: 'J707' },
  { id: 11, rollNumber: '111', studentName: 'Kevin Harris', admissionNumber: 'K808' },
  { id: 12, rollNumber: '112', studentName: 'Liam Clark', admissionNumber: 'L909' },
  { id: 13, rollNumber: '113', studentName: 'Mia Lewis', admissionNumber: 'M001' },
  { id: 14, rollNumber: '114', studentName: 'Noah Robinson', admissionNumber: 'N002' },
  { id: 15, rollNumber: '115', studentName: 'Olivia Walker', admissionNumber: 'O003' },
  { id: 16, rollNumber: '116', studentName: 'Paul Hall', admissionNumber: 'P004' },
  { id: 17, rollNumber: '117', studentName: 'Quinn Young', admissionNumber: 'Q005' },
  { id: 18, rollNumber: '118', studentName: 'Rachel Allen', admissionNumber: 'R006' },
  { id: 19, rollNumber: '119', studentName: 'Samuel King', admissionNumber: 'S007' },
  { id: 20, rollNumber: '120', studentName: 'Tina Wright', admissionNumber: 'T008' },
  { id: 21, rollNumber: '121', studentName: 'Uma Scott', admissionNumber: 'U009' },
  { id: 22, rollNumber: '122', studentName: 'Victor Green', admissionNumber: 'V010' },
  { id: 23, rollNumber: '123', studentName: 'Wendy Adams', admissionNumber: 'W011' },
  { id: 24, rollNumber: '124', studentName: 'Xander Baker', admissionNumber: 'X012' },
  { id: 25, rollNumber: '125', studentName: 'Yara Gonzalez', admissionNumber: 'Y013' },
  { id: 26, rollNumber: '126', studentName: 'Zachary Carter', admissionNumber: 'Z014' },
  { id: 27, rollNumber: '127', studentName: 'Ava Mitchell', admissionNumber: 'A015' },
  { id: 28, rollNumber: '128', studentName: 'Ben Perez', admissionNumber: 'B016' },
  { id: 29, rollNumber: '129', studentName: 'Cora Turner', admissionNumber: 'C017' },
  { id: 30, rollNumber: '130', studentName: 'Dylan Phillips', admissionNumber: 'D018' },
  { id: 31, rollNumber: '131', studentName: 'Eva Campbell', admissionNumber: 'E019' },
  { id: 32, rollNumber: '132', studentName: 'Finn Parker', admissionNumber: 'F020' },
  { id: 33, rollNumber: '133', studentName: 'Grace Evans', admissionNumber: 'G021' },
  { id: 34, rollNumber: '134', studentName: 'Henry Edwards', admissionNumber: 'H022' },
  { id: 35, rollNumber: '135', studentName: 'Ivy Collins', admissionNumber: 'I023' },
  { id: 36, rollNumber: '136', studentName: 'Jack Stewart', admissionNumber: 'J024' },
  { id: 37, rollNumber: '137', studentName: 'Kate Sanchez', admissionNumber: 'K025' },
  { id: 38, rollNumber: '138', studentName: 'Leo Morris', admissionNumber: 'L026' },
  { id: 39, rollNumber: '139', studentName: 'Maya Rivera', admissionNumber: 'M027' },
  { id: 40, rollNumber: '140', studentName: 'Nina Cooper', admissionNumber: 'N028' }
];