export const timetableData = {
    monday: [
        {
          id: 170,
          day: "MONDAY",
          sequence: 1,
          isBreak: false,
          startTime: "09:30:00",
          endTime: "10:15:00",
          roomNo: "1",
          staffName: "Ramesh Raina",
          subjectName: "Physics",
        },
        {
          id: 171,
          day: "MONDAY",
          sequence: 2,
          isBreak: false,
          startTime: "10:15:00",
          endTime: "11:00:00",
          roomNo: "2",
          staffName: "Suresh Raina",
          subjectName: "Chemistry",
        },
        {
          id: 172,
          day: "MONDAY",
          sequence: 3,
          isBreak: true,
          breakName: "",
          startTime: "11:00:00",
          endTime: "11:15:00",
          roomNo: null,
          staffName: null,
          subjectName: null,
        },
        {
          id: 173,
          day: "MONDAY",
          sequence: 4,
          isBreak: false,
          startTime: "11:15:00",
          endTime: "12:00:00",
          roomNo: "3",
          staffName: "Goku Raina",
          subjectName: "Math",
        },
        {
          id: 174,
          day: "MONDAY",
          sequence: 5,
          isBreak: false,
          startTime: "12:00:00",
          endTime: "12:45:00",
          roomNo: "4",
          staffName: "Olivia Raina",
          subjectName: "English",
        },
        {
          id: 175,
          day: "MONDAY",
          sequence: 6,
          isBreak: true,
          breakName: "Lunch",
          startTime: "12:45:00",
          endTime: "13:30:00",
          roomNo: null,
          staffName: null,
          subjectName: null,
        },
        {
          id: 176,
          day: "MONDAY",
          sequence: 7,
          isBreak: false,
          startTime: "13:30:00",
          endTime: "14:15:00",
          roomNo: "5",
          staffName: "Lily Raina",
          subjectName: "Biology",
        },
        {
          id: 177,
          day: "MONDAY",
          sequence: 8,
          isBreak: false,
          startTime: "14:15:00",
          endTime: "15:00:00",
          roomNo: "6",
          staffName: "Nadia Raina",
          subjectName: "History",
        },
        {
          id: 178,
          day: "MONDAY",
          sequence: 9,
          isBreak: true,
          breakName: "Short Break",
          startTime: "15:00:00",
          endTime: "15:15:00",
          roomNo: null,
          staffName: null,
          subjectName: null,
        },
        {
          id: 179,
          day: "MONDAY",
          sequence: 10,
          isBreak: false,
          startTime: "15:15:00",
          endTime: "16:00:00",
          roomNo: "7",
          staffName: "Rafiq Sheikh",
          subjectName: "Geography",
        },
        {
            id: 180,
            day: "MONDAY",
            sequence: 11,
            isBreak: false,
            startTime: "16:00:00",
            endTime: "16:45:00",
            roomNo: "7",
            staffName: "Rafiq Sheikh",
            subjectName: "Geography",
          },
      ],
    tuesday: [  {
        id: 170,
        day: "MONDAY",
        sequence: 1,
        isBreak: false,
        startTime: "09:30:00",
        endTime: "10:15:00",
        roomNo: "1",
        staffName: "Ramesh Raina",
        subjectName: "Physics",
      },
      {
        id: 171,
        day: "MONDAY",
        sequence: 2,
        isBreak: false,
        startTime: "10:15:00",
        endTime: "11:00:00",
        roomNo: "2",
        staffName: "Suresh Raina",
        subjectName: "Chemistry",
      },
      {
        id: 172,
        day: "MONDAY",
        sequence: 3,
        isBreak: true,
        breakName: "",
        startTime: "11:00:00",
        endTime: "11:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 173,
        day: "MONDAY",
        sequence: 4,
        isBreak: false,
        startTime: "11:15:00",
        endTime: "12:00:00",
        roomNo: "3",
        staffName: "Goku Raina",
        subjectName: "Math",
      },
      {
        id: 174,
        day: "MONDAY",
        sequence: 5,
        isBreak: false,
        startTime: "12:00:00",
        endTime: "12:45:00",
        roomNo: "4",
        staffName: "Olivia Raina",
        subjectName: "English",
      },
      {
        id: 175,
        day: "MONDAY",
        sequence: 6,
        isBreak: true,
        breakName: "Lunch",
        startTime: "12:45:00",
        endTime: "13:30:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 176,
        day: "MONDAY",
        sequence: 7,
        isBreak: false,
        startTime: "13:30:00",
        endTime: "14:15:00",
        roomNo: "5",
        staffName: "Lily Raina",
        subjectName: "Biology",
      },
      {
        id: 177,
        day: "MONDAY",
        sequence: 8,
        isBreak: false,
        startTime: "14:15:00",
        endTime: "15:00:00",
        roomNo: "6",
        staffName: "Nadia Raina",
        subjectName: "History",
      },
      {
        id: 178,
        day: "MONDAY",
        sequence: 9,
        isBreak: true,
        breakName: "Short Break",
        startTime: "15:00:00",
        endTime: "15:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 179,
        day: "MONDAY",
        sequence: 10,
        isBreak: false,
        startTime: "15:15:00",
        endTime: "16:00:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      }, {
        id: 180,
        day: "MONDAY",
        sequence: 11,
        isBreak: false,
        startTime: "16:00:00",
        endTime: "16:45:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      },],
    wednesday: [  {
        id: 170,
        day: "MONDAY",
        sequence: 1,
        isBreak: false,
        startTime: "09:30:00",
        endTime: "10:15:00",
        roomNo: "1",
        staffName: "Ramesh Raina",
        subjectName: "Physics",
      },
      {
        id: 171,
        day: "MONDAY",
        sequence: 2,
        isBreak: false,
        startTime: "10:15:00",
        endTime: "11:00:00",
        roomNo: "2",
        staffName: "Suresh Raina",
        subjectName: "Chemistry",
      },
      {
        id: 172,
        day: "MONDAY",
        sequence: 3,
        isBreak: true,
        breakName: "",
        startTime: "11:00:00",
        endTime: "11:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 173,
        day: "MONDAY",
        sequence: 4,
        isBreak: false,
        startTime: "11:15:00",
        endTime: "12:00:00",
        roomNo: "3",
        staffName: "Goku Raina",
        subjectName: "Math",
      },
      {
        id: 174,
        day: "MONDAY",
        sequence: 5,
        isBreak: false,
        startTime: "12:00:00",
        endTime: "12:45:00",
        roomNo: "4",
        staffName: "Olivia Raina",
        subjectName: "English",
      },
      {
        id: 175,
        day: "MONDAY",
        sequence: 6,
        isBreak: true,
        breakName: "Lunch",
        startTime: "12:45:00",
        endTime: "13:30:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 176,
        day: "MONDAY",
        sequence: 7,
        isBreak: false,
        startTime: "13:30:00",
        endTime: "14:15:00",
        roomNo: "5",
        staffName: "Lily Raina",
        subjectName: "Biology",
      },
      {
        id: 177,
        day: "MONDAY",
        sequence: 8,
        isBreak: false,
        startTime: "14:15:00",
        endTime: "15:00:00",
        roomNo: "6",
        staffName: "Nadia Raina",
        subjectName: "History",
      },
      {
        id: 178,
        day: "MONDAY",
        sequence: 9,
        isBreak: true,
        breakName: "Short Break",
        startTime: "15:00:00",
        endTime: "15:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 179,
        day: "MONDAY",
        sequence: 10,
        isBreak: false,
        startTime: "15:15:00",
        endTime: "16:00:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      }, {
        id: 180,
        day: "MONDAY",
        sequence: 11,
        isBreak: false,
        startTime: "16:00:00",
        endTime: "16:45:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      },],
    thursday:[  {
        id: 170,
        day: "MONDAY",
        sequence: 1,
        isBreak: false,
        startTime: "09:30:00",
        endTime: "10:15:00",
        roomNo: "1",
        staffName: "Ramesh Raina",
        subjectName: "Physics",
      },
      {
        id: 171,
        day: "MONDAY",
        sequence: 2,
        isBreak: false,
        startTime: "10:15:00",
        endTime: "11:00:00",
        roomNo: "2",
        staffName: "Suresh Raina",
        subjectName: "Chemistry",
      },
      {
        id: 172,
        day: "MONDAY",
        sequence: 3,
        isBreak: true,
        breakName: "",
        startTime: "11:00:00",
        endTime: "11:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 173,
        day: "MONDAY",
        sequence: 4,
        isBreak: false,
        startTime: "11:15:00",
        endTime: "12:00:00",
        roomNo: "3",
        staffName: "Goku Raina",
        subjectName: "Math",
      },
      {
        id: 174,
        day: "MONDAY",
        sequence: 5,
        isBreak: false,
        startTime: "12:00:00",
        endTime: "12:45:00",
        roomNo: "4",
        staffName: "Olivia Raina",
        subjectName: "English",
      },
      {
        id: 175,
        day: "MONDAY",
        sequence: 6,
        isBreak: true,
        breakName: "Lunch",
        startTime: "12:45:00",
        endTime: "13:30:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 176,
        day: "MONDAY",
        sequence: 7,
        isBreak: false,
        startTime: "13:30:00",
        endTime: "14:15:00",
        roomNo: "5",
        staffName: "Lily Raina",
        subjectName: "Biology",
      },
      {
        id: 177,
        day: "MONDAY",
        sequence: 8,
        isBreak: false,
        startTime: "14:15:00",
        endTime: "15:00:00",
        roomNo: "6",
        staffName: "Nadia Raina",
        subjectName: "History",
      },
      {
        id: 178,
        day: "MONDAY",
        sequence: 9,
        isBreak: true,
        breakName: "Short Break",
        startTime: "15:00:00",
        endTime: "15:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 179,
        day: "MONDAY",
        sequence: 10,
        isBreak: false,
        startTime: "15:15:00",
        endTime: "16:00:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      }, {
        id: 180,
        day: "MONDAY",
        sequence: 11,
        isBreak: false,
        startTime: "16:00:00",
        endTime: "16:45:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      },],
    friday: [  {
        id: 170,
        day: "MONDAY",
        sequence: 1,
        isBreak: false,
        startTime: "09:30:00",
        endTime: "10:15:00",
        roomNo: "1",
        staffName: "Ramesh Raina",
        subjectName: "Physics",
      },
      {
        id: 171,
        day: "MONDAY",
        sequence: 2,
        isBreak: false,
        startTime: "10:15:00",
        endTime: "11:00:00",
        roomNo: "2",
        staffName: "Suresh Raina",
        subjectName: "Chemistry",
      },
      {
        id: 172,
        day: "MONDAY",
        sequence: 3,
        isBreak: true,
        breakName: "Short Break",
        startTime: "11:00:00",
        endTime: "11:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 173,
        day: "MONDAY",
        sequence: 4,
        isBreak: false,
        startTime: "11:15:00",
        endTime: "12:00:00",
        roomNo: "3",
        staffName: "Goku Raina",
        subjectName: "Math",
      },
      {
        id: 174,
        day: "MONDAY",
        sequence: 5,
        isBreak: false,
        startTime: "12:00:00",
        endTime: "12:45:00",
        roomNo: "4",
        staffName: "Olivia Raina",
        subjectName: "English",
      },
      {
        id: 175,
        day: "MONDAY",
        sequence: 6,
        isBreak: true,
        breakName: "Lunch",
        startTime: "12:45:00",
        endTime: "13:30:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 176,
        day: "MONDAY",
        sequence: 7,
        isBreak: false,
        startTime: "13:30:00",
        endTime: "14:15:00",
        roomNo: "5",
        staffName: "Lily Raina",
        subjectName: "Biology",
      },
      {
        id: 177,
        day: "MONDAY",
        sequence: 8,
        isBreak: false,
        startTime: "14:15:00",
        endTime: "15:00:00",
        roomNo: "6",
        staffName: "Nadia Raina",
        subjectName: "History",
      },
      {
        id: 178,
        day: "MONDAY",
        sequence: 9,
        isBreak: true,
        breakName: "Short Break",
        startTime: "15:00:00",
        endTime: "15:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 179,
        day: "MONDAY",
        sequence: 10,
        isBreak: false,
        startTime: "15:15:00",
        endTime: "16:00:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      }, {
        id: 180,
        day: "MONDAY",
        sequence: 11,
        isBreak: false,
        startTime: "16:00:00",
        endTime: "16:45:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      },],
    saturday: [  {
        id: 170,
        day: "MONDAY",
        sequence: 1,
        isBreak: false,
        startTime: "09:30:00",
        endTime: "10:15:00",
        roomNo: "1",
        staffName: "Ramesh Raina",
        subjectName: "Physics",
      },
      {
        id: 171,
        day: "MONDAY",
        sequence: 2,
        isBreak: false,
        startTime: "10:15:00",
        endTime: "11:00:00",
        roomNo: "2",
        staffName: "Suresh Raina",
        subjectName: "Chemistry",
      },
      {
        id: 172,
        day: "MONDAY",
        sequence: 3,
        isBreak: true,
        breakName: "Short Break",
        startTime: "11:00:00",
        endTime: "11:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 173,
        day: "MONDAY",
        sequence: 4,
        isBreak: false,
        startTime: "11:15:00",
        endTime: "12:00:00",
        roomNo: "3",
        staffName: "Goku Raina",
        subjectName: "Math",
      },
      {
        id: 174,
        day: "MONDAY",
        sequence: 5,
        isBreak: false,
        startTime: "12:00:00",
        endTime: "12:45:00",
        roomNo: "4",
        staffName: "Olivia Raina",
        subjectName: "English",
      },
      {
        id: 175,
        day: "MONDAY",
        sequence: 6,
        isBreak: true,
        breakName: "Lunch",
        startTime: "12:45:00",
        endTime: "13:30:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 176,
        day: "MONDAY",
        sequence: 7,
        isBreak: false,
        startTime: "13:30:00",
        endTime: "14:15:00",
        roomNo: "5",
        staffName: "Lily Raina",
        subjectName: "Biology",
      },
      {
        id: 177,
        day: "MONDAY",
        sequence: 8,
        isBreak: false,
        startTime: "14:15:00",
        endTime: "15:00:00",
        roomNo: "6",
        staffName: "Nadia Raina",
        subjectName: "History",
      },
      {
        id: 178,
        day: "MONDAY",
        sequence: 9,
        isBreak: true,
        breakName: "Short Break",
        startTime: "15:00:00",
        endTime: "15:15:00",
        roomNo: null,
        staffName: null,
        subjectName: null,
      },
      {
        id: 179,
        day: "MONDAY",
        sequence: 10,
        isBreak: false,
        startTime: "15:15:00",
        endTime: "16:00:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      }, {
        id: 180,
        day: "MONDAY",
        sequence: 11,
        isBreak: false,
        startTime: "16:00:00",
        endTime: "16:45:00",
        roomNo: "7",
        staffName: "Rafiq Sheikh",
        subjectName: "Geography",
      },],
  };

  export const teachertimetable ={
    monday: [
      { period: 1, subject: "Physics", subjectCode: "PHY", timing: "09:30 AM - 10:15 AM", class: 6, section: "A" },
      { period: 2, subject: "Chemistry", subjectCode: "CHE", timing: "10:15 AM - 11:00 AM", class: 6, section: "D" },
      { period: 3, subject: "Short Break", subjectCode: "BREAK", timing: "11:00 AM - 11:15 AM", class: null, section: null },
      { period: 4, subject: "Math", subjectCode: "MATH", timing: "11:15 AM - 12:00 PM", class: 7, section: "A" },
      { period: 5, subject: "English", subjectCode: "ENG", timing: "12:00 PM - 12:45 PM", class: 8, section: "B" },
      { period: 6, subject: "Lunch", subjectCode: "BREAK", timing: "12:45 PM - 01:30 PM", class: null, section: null },
      { period: 7, subject: "Biology", subjectCode: "BIO", timing: "01:30 PM - 02:15 PM", class: 7, section: "B" },
      { period: 8, subject: "History", subjectCode: "HIST", timing: "02:15 PM - 03:00 PM", class: 9, section: "A" },
      { period: 9, subject: "Short Break", subjectCode: "BREAK", timing: "03:00 PM - 03:15 PM", class: null, section: null },
      { period: 10, subject: "Geography", subjectCode: "GEO", timing: "03:15 PM - 04:00 PM", class: 10, section: "B" },
      { period: 11, subject: "Geography", subjectCode: "GEO", timing: "04:00 PM - 04:45 PM", class: 10, section: "B" },
    ],
    tuesday: [
      { period: 1, subject: "Mathematics", subjectCode: "MATH", timing: "09:30 AM - 10:15 AM", class: 6, section: "A" },
      { period: 2, subject: "English", subjectCode: "ENG", timing: "10:15 AM - 11:00 AM", class: 6, section: "B" },
      { period: 3, subject: "Short Break", subjectCode: "BREAK", timing: "11:00 AM - 11:15 AM", class: null, section: null },
      { period: 4, subject: "Science", subjectCode: "SCI", timing: "11:15 AM - 12:00 PM", class: 7, section: "A" },
      { period: 5, subject: "Social Studies", subjectCode: "SS", timing: "12:00 PM - 12:45 PM", class: 8, section: "A" },
      { period: 6, subject: "Lunch", subjectCode: "BREAK", timing: "12:45 PM - 01:30 PM", class: null, section: null },
      { period: 7, subject: "Physics", subjectCode: "PHY", timing: "01:30 PM - 02:15 PM", class: 9, section: "A" },
      { period: 8, subject: "Chemistry", subjectCode: "CHE", timing: "02:15 PM - 03:00 PM", class: 10, section: "B" },
      { period: 9, subject: "Short Break", subjectCode: "BREAK", timing: "03:00 PM - 03:15 PM", class: null, section: null },
      { period: 10, subject: "Biology", subjectCode: "BIO", timing: "03:15 PM - 04:00 PM", class: 9, section: "B" },
      { period: 11, subject: "Biology", subjectCode: "BIO", timing: "04:00 PM - 04:45 PM", class: 9, section: "B" },
    ],
    wednesday: [
      { period: 1, subject: "English", subjectCode: "ENG", timing: "09:30 AM - 10:15 AM", class: 6, section: "A" },
      { period: 2, subject: "History", subjectCode: "HIST", timing: "10:15 AM - 11:00 AM", class: 6, section: "B" },
      { period: 3, subject: "Short Break", subjectCode: "BREAK", timing: "11:00 AM - 11:15 AM", class: null, section: null },
      { period: 4, subject: "Mathematics", subjectCode: "MATH", timing: "11:15 AM - 12:00 PM", class: 7, section: "A" },
      { period: 5, subject: "Science", subjectCode: "SCI", timing: "12:00 PM - 12:45 PM", class: 8, section: "B" },
      { period: 6, subject: "Lunch", subjectCode: "BREAK", timing: "12:45 PM - 01:30 PM", class: null, section: null },
      { period: 7, subject: "Geography", subjectCode: "GEO", timing: "01:30 PM - 02:15 PM", class: 9, section: "A" },
      { period: 8, subject: "Chemistry", subjectCode: "CHE", timing: "02:15 PM - 03:00 PM", class: 10, section: "B" },
      { period: 9, subject: "Short Break", subjectCode: "BREAK", timing: "03:00 PM - 03:15 PM", class: null, section: null },
      { period: 10, subject: "Biology", subjectCode: "BIO", timing: "03:15 PM - 04:00 PM", class: 9, section: "B" },
      { period: 11, subject: "Physical Education", subjectCode: "PE", timing: "04:00 PM - 04:45 PM", class: 10, section: "A" },
    ],
    thursday: [
      { period: 1, subject: "Mathematics", subjectCode: "MATH", timing: "09:30 AM - 10:15 AM", class: 6, section: "A" },
      { period: 2, subject: "English", subjectCode: "ENG", timing: "10:15 AM - 11:00 AM", class: 6, section: "B" },
      { period: 3, subject: "Short Break", subjectCode: "BREAK", timing: "11:00 AM - 11:15 AM", class: null, section: null },
      { period: 4, subject: "Physics", subjectCode: "PHY", timing: "11:15 AM - 12:00 PM", class: 7, section: "A" },
      { period: 5, subject: "Social Studies", subjectCode: "SS", timing: "12:00 PM - 12:45 PM", class: 8, section: "A" },
      { period: 6, subject: "Lunch", subjectCode: "BREAK", timing: "12:45 PM - 01:30 PM", class: null, section: null },
      { period: 7, subject: "Biology", subjectCode: "BIO", timing: "01:30 PM - 02:15 PM", class: 9, section: "B" },
      { period: 8, subject: "History", subjectCode: "HIST", timing: "02:15 PM - 03:00 PM", class: 10, section: "B" },
      { period: 9, subject: "Short Break", subjectCode: "BREAK", timing: "03:00 PM - 03:15 PM", class: null, section: null },
      { period: 10, subject: "Art", subjectCode: "ART", timing: "03:15 PM - 04:00 PM", class: 10, section: "A" },
      { period: 11, subject: "Art", subjectCode: "ART", timing: "04:00 PM - 04:45 PM", class: 10, section: "A" },
    ],
    friday: [
      { period: 1, subject: "Physics", subjectCode: "PHY", timing: "09:30 AM - 10:15 AM", class: 6, section: "A" },
      { period: 2, subject: "Chemistry", subjectCode: "CHE", timing: "10:15 AM - 11:00 AM", class: 6, section: "B" },
      { period: 3, subject: "Short Break", subjectCode: "BREAK", timing: "11:00 AM - 11:15 AM", class: null, section: null },
      { period: 4, subject: "Mathematics", subjectCode: "MATH", timing: "11:15 AM - 12:00 PM", class: 7, section: "A" },
      { period: 5, subject: "English", subjectCode: "ENG", timing: "12:00 PM - 12:45 PM", class: 8, section: "B" },
      { period: 6, subject: "Lunch", subjectCode: "BREAK", timing: "12:45 PM - 01:30 PM", class: null, section: null },
      { period: 7, subject: "Geography", subjectCode: "GEO", timing: "01:30 PM - 02:15 PM", class: 9, section: "A" },
      { period: 8, subject: "Biology", subjectCode: "BIO", timing: "02:15 PM - 03:00 PM", class: 10, section: "B" },
      { period: 9, subject: "Short Break", subjectCode: "BREAK", timing: "03:00 PM - 03:15 PM", class: null, section: null },
      { period: 10, subject: "Physical Education", subjectCode: "PE", timing: "03:15 PM - 04:00 PM", class: 10, section: "A" },
      { period: 11, subject: "Physical Education", subjectCode: "PE", timing: "04:00 PM - 04:45 PM", class: 10, section: "A" },
    ],
    saturday: [
      { period: 1, subject: "English", subjectCode: "ENG", timing: "09:30 AM - 10:15 AM", class: 6, section: "A" },
      { period: 2, subject: "Mathematics", subjectCode: "MATH", timing: "10:15 AM - 11:00 AM", class: 6, section: "B" },
      { period: 3, subject: "Short Break", subjectCode: "BREAK", timing: "11:00 AM - 11:15 AM", class: null, section: null },
      { period: 4, subject: "Science", subjectCode: "SCI", timing: "11:15 AM - 12:00 PM", class: 7, section: "A" },
      { period: 5, subject: "History", subjectCode: "HIST", timing: "12:00 PM - 12:45 PM", class: 8, section: "B" },
      { period: 6, subject: "Lunch", subjectCode: "BREAK", timing: "12:45 PM - 01:30 PM", class: null, section: null },
      { period: 7, subject: "Biology", subjectCode: "BIO", timing: "01:30 PM - 02:15 PM", class: 9, section: "A" },
      { period: 8, subject: "Chemistry", subjectCode: "CHE", timing: "02:15 PM - 03:00 PM", class: 10, section: "B" },
      { period: 9, subject: "Short Break", subjectCode: "BREAK", timing: "03:00 PM - 03:15 PM", class: null, section: null },
      { period: 10, subject: "Art", subjectCode: "ART", timing: "03:15 PM - 04:00 PM", class: 10, section: "A" },
      { period: 11, subject: "Art", subjectCode: "ART", timing: "04:00 PM - 04:45 PM", class: 10, section: "A" },
    ],
  };
  