export const staffsData = [
  {
    id: "1",
    staffName: "Ravi Kumar",
    staffID: "T001",
    role: "Super Admin",
    department: "Admin",
    designation: "Technical Head",
    mobileNumber: "9876543210",
    panNum: "ABCDE1234F",
    fathername: "raj",
    mothername: "kaveri",
    gender: "male",
    email: "pathi@123",
    dob: "03-12-1999",
    doj: "03-04-2023",
    emergencyContactNumber: "9836353333",
    maritalStatus: "unMarried",
    address: "Nandanam",
    permanentAddress: "Nandanam",
    Qualification: "BE",
    WorkExperience: "1",
    note: "Note",
    epfNo: "563",
    basicSalary: "25000",
    contractType: "youraj",
    workShoft: "day",
    workLocation: "Channai",
    bankTitle: "ICICI",
    bankAccountNo: "1234",
    bankName: "ICICI",
    ifscCode: "ICICI123",
    bankBranchName: "Nandanam"

  },
  {
    id: "2",
    staffName: "Lakshmi Narayan",
    staffID: "T002",
    role: "Admin",
    department: "Admin",
    designation: "Principal",
    mobileNumber: "9876543210",
    panNum: "ABCDE1234F",
    fathername: "raj",
    mothername: "kaveri",
    gender: "male",
    email: "pathi@123",
    dob: "03-12-1999",
    doj: "03-04-2023",
    emergencyContactNumber: "9836353333",
    maritalStatus: "unMarried",
    address: "Nandanam",
    permanentAddress: "Nandanam",
    Qualification: "BE",
    WorkExperience: "1",
    note: "",
    epfNo: "563",
    basicSalary: "25000",
    contractType: "youraj",
    workShoft: "day",
    workLocation: "Channai",
    bankTitle: "ICICI",
    bankAccountNo: "1234",
    bankName: "ICICI",
    ifscCode: "ICICI123",
    bankBranchName: "Nandanam"
  },
  {
    id: "3",
    staffName: "Suresh Babu",
    staffID: "T003",
    role: "Teacher",
    department: "Academic",
    designation: "Faculty",
    mobileNumber: "9876543210",
    panNum: "ABCDE1234F",
    fathername: "raj",
    mothername: "kaveri",
    gender: "male",
    email: "pathi@123",
    dob: "03-12-1999",
    doj: "03-04-2023",
    emergencyContactNumber: "9836353333",
    maritalStatus: "unMarried",
    address: "Nandanam",
    permanentAddress: "Nandanam",
    Qualification: "BE",
    WorkExperience: "1",
    note: "",
    epfNo: "563",
    basicSalary: "25000",
    contractType: "youraj",
    workShoft: "day",
    workLocation: "Channai",
    bankTitle: "ICICI",
    bankAccountNo: "1234",
    bankName: "ICICI",
    ifscCode: "ICICI123",
    bankBranchName: "Nandanam"
  },
  {
    id: "4",
    staffName: "Meera Iyer",
    staffID: "T004",
    role: "Admin",
    department: "Admin",
    designation: "Vice Principal",
    mobileNumber: "9876543210",
    panNum: "ABCDE1234F",
    fathername: "raj",
    mothername: "kaveri",
    gender: "male",
    email: "pathi@123",
    dob: "03-12-1999",
    doj: "03-04-2023",
    emergencyContactNumber: "9836353333",
    maritalStatus: "unMarried",
    address: "Nandanam",
    permanentAddress: "Nandanam",
    Qualification: "BE",
    WorkExperience: "1",
    note: "",
    epfNo: "563",
    basicSalary: "25000",
    contractType: "youraj",
    workShoft: "day",
    workLocation: "Channai",
    bankTitle: "ICICI",
    bankAccountNo: "1234",
    bankName: "ICICI",
    ifscCode: "ICICI123",
    bankBranchName: "Nandanam"
  },
  {
    id: "5",
    staffName: "Anand Raj",
    staffID: "T005",
    role: "Teacher",
    department: "Academic",
    designation: "Faculty",
    mobileNumber: "9876543210",
    panNum: "ABCDE1234F",
    fathername: "raj",
    mothername: "kaveri",
    gender: "male",
    email: "pathi@123",
    dob: "03-12-1999",
    doj: "03-04-2023",
    emergencyContactNumber: "9836353333",
    maritalStatus: "unMarried",
    address: "Nandanam",
    permanentAddress: "Nandanam",
    Qualification: "BE",
    WorkExperience: "1",
    note: "",
    epfNo: "563",
    basicSalary: "25000",
    contractType: "youraj",
    workShoft: "day",
    workLocation: "Channai",
    bankTitle: "ICICI",
    bankAccountNo: "1234",
    bankName: "ICICI",
    ifscCode: "ICICI123",
    bankBranchName: "Nandanam"
  },
  {
    id: "6",
    staffName: "Ravi Kumar",
    staffID: "T006",
    role: "Super Admin",
    department: "Admin",
    designation: "Technical Head",
    mobileNumber: "9876543210",
    panNum: "ABCDE1234F",
    fathername: "raj",
    mothername: "kaveri",
    gender: "male",
    email: "pathi@123",
    dob: "03-12-1999",
    doj: "03-04-2023",
    emergencyContactNumber: "9836353333",
    maritalStatus: "unMarried",
    address: "Nandanam",
    permanentAddress: "Nandanam",
    Qualification: "BE",
    WorkExperience: "1",
    note: "",
    epfNo: "563",
    basicSalary: "25000",
    contractType: "youraj",
    workShoft: "day",
    workLocation: "Channai",
    bankTitle: "ICICI",
    bankAccountNo: "1234",
    bankName: "ICICI",
    ifscCode: "ICICI123",
    bankBranchName: "Nandanam"
  },
]