export const legends = [
    {
      id: "1",
      name: "Total present(P)",
      key: "P",
      color: "#31AD76",
    },
    {
      id: "2",
      name: "Total Late(L)",
      key: "L",
      color: "#F1A245",
    },
    {
      id: "3",
      name: "Total Absent(A)",
      key: "A",
      color: "#E56A6C",
    },
    {
      id: "4",
      name: "Total Half Day(F)",
      key: "F",
      color: "#2ACCCB",
    },
    {
      id: "5",
      name: "Total Holiday(H)",
      key: "H",
      color: "#65B2FC",
    },
  ];
  
  export const statusColor = (key) => {
    return key === "P"
      ? "#31AD76"
      : key === "A"
        ? "#E56A6C"
        : key === "L"
          ? "#F1A245"
          : key === "F"
            ? "#2ACCCB"
            : key === "H"
              ? "#65B2FC"
              : "#263446";
  };
  
  export const attendanceData = [
    {
      day: 1,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 2,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 3,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 4,
      Jan: "A",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 5,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 6,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 7,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 8,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 9,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 10,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 11,
      Jan: "L",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 12,
      Jan: "H",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 13,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 14,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 15,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 16,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 17,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 18,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 19,
      Jan: "F",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 20,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 21,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 22,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 23,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 24,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 25,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 26,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 27,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 28,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 29,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 30,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
    {
      day: 31,
      Jan: "P",
      Feb: "-",
      Mar: "-",
      Apr: "-",
      May: "-",
      Jun: "-",
      Jul: "-",
      Aug: "-",
      Sep: "-",
      Oct: "-",
      Nov: "-",
      Dec: "-",
    },
  ];
  export const logtableData = [
    {
      id: "1",
      Payslip: "9000",
      MonthYear: "Joe Black",
      Date: "Super Admin",
      Mode: "Cash",
      Status: "Paid",
      NetSalary: "45,000.00",
      Action: "View Payslip"
    },
    {
      id: "1",
      Payslip: "9000",
      MonthYear: "Joe Black",
      Date: "Super Admin",
      Mode: "",
      Status: "Generated",
      NetSalary: "45,000.00",
      Action: ""
    }
  
  ]
  export const mockAttendanceData = {
    January: [
      { day: 1, value: 8, goal: 8, status: "Present" },
      // { day: 2, value: 3, goal: 8, status: "Late" },
      { day: 3, value: 8, goal: 8, status: "Absent" },
      // { day: 4, value: 5, goal: 8, status: "Half Day" },
      { day: 5, value: 8, goal: 8, status: "Holiday" },
      // Continue for all days...
    ],
    February: [
      { day: 1, value: 7, goal: 8, status: "Present" },
      // { day: 2, value: 6, goal: 8, status: "Late" },
      { day: 3, value: 8, goal: 8, status: "Absent" },
      // { day: 4, value: 4, goal: 8, status: "Half Day" },
      { day: 5, value: 8, goal: 8, status: "Holiday" },
      // Continue for all days...
    ],
    March: [
      { day: 1, value: 8, goal: 8, status: "Present" },
      { day: 2, value: 8, goal: 8, status: "Absent" },
      // { day: 3, value: 6, goal: 8, status: "Late" },
      { day: 4, value: 8, goal: 8, status: "Holiday" },
      { day: 5, value: 4, goal: 8, status: "Half Day" },
      // Continue for all days...
    ],
    September: [
      { day: 1, value: 8, goal: 8, status: "Present" },
      // { day: 2, value: 4, goal: 8, status: "Half Day" },
      { day: 3, value: 8, goal: 8, status: "Absent" },
      { day: 4, value: 8, goal: 8, status: "Holiday" },
      { day: 5, value: 8, goal: 8, status: "Present" },
      // { day: 6, value: 6, goal: 8, status: "Late" },
      { day: 7, value: 8, goal: 8, status: "Present" },
      { day: 8, value: 8, goal: 8, status: "Absent" },
      // Continue for all days...
    ],
    // Add more months as necessary...
  };
  
  