export const examTable = [
  {
    sub: "English (210)",
    maxmark: "100.00",
    minMark: "33.00",
    marksObtained: "56.00",
    result: "Pass",
    note: "-",
  },
  {
    sub: "Mathematics (110)",
    maxmark: "100.00",
    minMark: "33.00",
    marksObtained: "56.00",
    result: "Pass",
    note: "-",
  },
  {
    sub: "Hindi (230)",
    maxmark: "100.00",
    minMark: "33.00",
    marksObtained: "56.00",
    result: "Pass",
    note: "-",
  },
  {
    sub: "Science (111)",
    maxmark: "100.00",
    minMark: "33.00",
    marksObtained: "56.00",
    result: "Pass",
    note: "-",
  },
];

export const fessTable = [
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 +0.00",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Paid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "Cash",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "-",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Partial",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "1,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 +0.00",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Paid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "Cash",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "-",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Partial",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "1,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
  {
    feesGroup: "class 1",
    feesCode: "Admission-fees",
    dueDate: "04/10/2024",
    status: "Unpaid",
    amount: "2,000.00 ",
    payment: "-",
    mode: "-",
    date: "05/02/2024",
    discount: "0.00",
    fine: "0.00",
    paid: "0.00",
    balance: "2,000.00",
  },
];

export const documentTable = [
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
  {
    title: "Transfer Certificate",
    fileName: "Transfer_Certificate.pdf",
    action: "",
  },
];
